### ISSUE TITLE
Hello, I love the intention of your script, however:

### ISSUE THREAD

**Issue by studioqqq** [OndrejMalek/devilspie2saveWindowSizeAndPosition#1]
$ ls .config/devilspie2/ ; devilspie2 
debug.lua  devilspie2.lua  devilspie2saveWindowSizeAndPosition-master  lib  load_window_state.lua  README.md  save_window_state.lua
Error: ....config/devilspie2/lib/save_window_state_commons.lua:18: attempt to concatenate a nil value
Error: ....config/devilspie2/lib/save_window_state_commons.lua:18: attempt to concatenate a nil value
Error: ....config/devilspie2/lib/save_window_state_commons.lua:18: attempt to concatenate a nil value
Error: ....config/devilspie2/lib/save_window_state_commons.lua:18: attempt to concatenate a nil value
Error: ....config/devilspie2/lib/save_window_state_commons.lua:18: attempt to concatenate a nil value
Error: ....config/devilspie2/lib/save_window_state_commons.lua:18: attempt to concatenate a nil value
Error: ....config/devilspie2/lib/save_window_state_commons.lua:18: attempt to concatenate a nil value
Error: ....config/devilspie2/lib/save_window_state_commons.lua:18: attempt to concatenate a nil value
Error: ....config/devilspie2/lib/save_window_state_commons.lua:18: attempt to concatenate a nil value
Error: ....config/devilspie2/lib/save_window_state_commons.lua:18: attempt to concatenate a nil value

**Comment by OndrejMalek** [comment]
Hi, thx for issue. I have done changes to master. Seems working now. I was using it passed two years, but forgot to push changes to github. It is not 100%, because some programs are setting their positions by themselves.
